### ISSUE TITLE
Remove default assembly for GRCGenome.download

### ISSUE THREAD

**Issue by eblume** [eblume/Tiger-Lily#20]
Currently there is a variable in `tigerlily.grc.genome` called `DEFAULT_ASSEMBLY` that provides a default assembly to download. There's really no reason to have this and it should be removed.

Make sure to update the relevant documentation and unit tests as necessary. There might also be a change needed to the genome assembly download cookbook recipe.

**Comment by fuzzylogical** [comment]
removed DEFAULT ASSEMBLY and now it just does a download of a specified assembly
