### ISSUE TITLE
Verify GRC genome downloads vs md5sums

### ISSUE THREAD

**Issue by eblume** [eblume/Tiger-Lily#7]
There should be a way to specify either hard-coded or URL-addressed md5sums (or other digest verifications) for downloaded reference genomes.

At first glance it seems that the UCSC Genome Browser provides this file for every release, although I think some of them might have changing names.

Downloads should automatically grab these digests and verify the download, and automatically re-download in the case of failure. There should also be an optional argument to the download method to suppress verification, as well as an additional optional argument that should turn off automatic re-download on verification failure (and raise an exception instead).

This will likely become a slated feature for 0.2 or 0.3

**Comment by eblume** [comment]
This is officially being slated as a 0.2 feature.

**Comment by eblume** [comment]
Assigning to Euclid since he is working on it now

**Comment by fuzzylogical** [comment]
not yet committed but seems like it works going to test a little to make sure the tests are solid

**Comment by eblume** [comment]
Sounds cool!

**Comment by fuzzylogical** [comment]
changed code to fit unit tests seems to work solidly

**Comment by eblume** [comment]
You're ALMOST done, you just forgot to update the documentation.
